# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Add-in.
# ------------------------------------------------------

# This is a reminder that you are using a generated .pro file.
# Remove it when you are finished editing this file.

TEMPLATE = subdirs
SUBDIRS += graphs/graphs.pro \
    3rd_party/qwt/qwt.pro \
    exel_reader \
    document_system \
    math_system
